FROM centos:7

# Fix CentOS 7 repos (EOL)
RUN sed -i 's|mirrorlist=|#mirrorlist=|g' /etc/yum.repos.d/CentOS-* && \
    sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*

RUN yum -y install epel-release


# Install XFCE desktop + VNC + Python
RUN yum -y groupinstall "Xfce" && \
    yum -y install tigervnc-server dbus-x11 python3 python3-pip

# Create a user for VNC
RUN useradd -m dockeruser && \
    echo "dockeruser:docker" | chpasswd

# Configure VNC password
RUN mkdir /home/dockeruser/.vnc && \
    echo "docker" | vncpasswd -f > /home/dockeruser/.vnc/passwd && \
    chmod 600 /home/dockeruser/.vnc/passwd && \
    chown -R dockeruser:dockeruser /home/dockeruser/.vnc

# Start XFCE when VNC starts
RUN echo "startxfce4" > /home/dockeruser/.vnc/xstartup && \
    chmod +x /home/dockeruser/.vnc/xstartup

# Copy your Python app
COPY . /app
WORKDIR /app

# Install Python dependencies
RUN pip3 install -r requirements.txt

EXPOSE 5901

CMD ["su", "-", "dockeruser", "-c", "vncserver :1 -geometry 1280x800 -depth 24 && tail -f /dev/null"]
